image: node:10
stages:
    - test

variables:
    DOCKER_DRIVER: overlay2

before_script:
    - npm install

test:
    stage: test
    script:
        - echo $CI_PIPELINE_SOURCE
        - echo $CI_JOB_TOKEN
        - npm show ipfs version
        - echo "npm install && npm install ipfs@`npm show ipfs version --tag next` && npm test"
        - "false"
    only:
        - master

