image: node:10
stages:
  - test

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - npm ci -q

test:
  stage: test
  script:
    - echo $CI_PIPELINE_SOURCE
    - echo $CI_JOB_TOKEN
    - npm show ipfs version
    - "npm install ipfs@`npm show ipfs-ci-test version --tag next` && npm test"
  only:
    variables:
       - $CI_PIPELINE_SOURCE == "pipeline"
